### ISSUE TITLE
Incorrect output for find_near_matches with two strings of the same length?

### ISSUE THREAD

**Issue by Ericxgao** [taleinat/fuzzysearch#15]
Is this behavior intended? If so - why?

When I do:
`matches = find_near_matches('AAAA', 'ZZZZ', max_l_dist=4)`

There are no matches, despite the fact that AAAA can become ZZZZ with 4 substitutions. Am I misinterpreting something here?

**Comment by taleinat** [comment]
That looks like a bug! I'll check it out.

**Comment by taleinat** [comment]
Fixed in commit a8219a04, released in v0.6.2.

Thanks for reporting this, @Ericxgao!
