### ISSUE TITLE
fuzzysearch on conda-forge

### ISSUE THREAD

**Issue by klauer** [taleinat/fuzzysearch#24]
Hi @taleinat,

I wanted to let you know that fuzzysearch is now available for conda users via conda-forge.
It's building the Cython extension for OSX/Windows/Linux with Python 3.6/3.7/3.8 and also pypy (hopefully). 

For those unfamiliar with conda, it's easy to install through: `conda install -c conda-forge fuzzysearch`.

In any case, if you'd like to be a maintainer of the feedstock (https://github.com/conda-forge/fuzzysearch-feedstock) which generates the builds, let me know as I'd be happy to add you. Thanks for the great library!

**Comment by taleinat** [comment]
Hi @klauer, thanks for the notice!

If having a conda-forge feedstock for fuzzysearch makes it more readily available for more users, that sounds good to me! I won't be able to help maintaining it, though.
