### ISSUE TITLE
Can we get "dist" value in float instead of integer

### ISSUE THREAD

**Issue by sasi143** [taleinat/fuzzysearch#26]
`[Match(start=21, end=28, dist=6, matched=':228621'),
 Match(start=22, end=28, dist=5, matched='228621'),
 Match(start=23, end=28, dist=6, matched='28621'),
 Match(start=21, end=28, dist=6, matched=':228621'),
 Match(start=22, end=28, dist=5, matched='228621'),
 Match(start=23, end=28, dist=6, matched='28621'),
 Match(start=21, end=28, dist=6, matched=':228621'),
 Match(start=22, end=28, dist=5, matched='228621'),
 Match(start=23, end=28, dist=6, matched='28621'),
 Match(start=21, end=28, dist=6, matched=':228621'),
 Match(start=22, end=28, dist=5, matched='228621'),
 Match(start=23, end=28, dist=6, matched='28621'),
 Match(start=21, end=28, dist=6, matched=':228621'),
 Match(start=22, end=28, dist=5, matched='228621'),
 Match(start=23, end=28, dist=6, matched='28621'),
 Match(start=21, end=28, dist=6, matched=':228621'),
 Match(start=22, end=28, dist=5, matched='228621'),
 Match(start=23, end=28, dist=6, matched='28621'),
 Match(start=21, end=28, dist=6, matched=':228621'),
 Match(start=22, end=28, dist=5, matched='228621'),
 Match(start=23, end=28, dist=6, matched='28621')]`

We are getting dist value in integer and its become hard to pick the best value because if you see above output 5 is the least dist value but a lot of values are coming with dist=5

if we have dist value in float like **dist = 5.1 or 5.4 or 6.1 e.t.c**

Let me know, what are the possibilities

**Comment by taleinat** [comment]
Hi @sasi143,

Which function are you running to get that output? `find_near_matches()` makes sure not to return such overlapping matches, returning the best result (lowest distance, and the longest amongst those).

If you're running one of the internal functions, have you tried running the list of matches through `fuzzysearch.common.consolidate_overlapping_matches()`? You can see an example of doing this on the [usage page of the docs](https://github.com/taleinat/fuzzysearch/blob/master/docs/usage.rst).

**Comment by taleinat** [comment]
@sasi143, in addition to the above, fuzzysearch consistently uses the Levenshtein distance, which is by definition integral. If you'd like to suggest supporting difference distance metrics, that could be interesting, but please provide a reference to which specific distance metric you mean.

**Comment by taleinat** [comment]
I'm closing this due to the suggested behavior of returning a fractional distance being very unclear, and a lack of further response from the poster (@sasi143).
