### ISSUE TITLE
Call with looser 

### ISSUE THREAD

**Issue by DanielBiskup** [taleinat/fuzzysearch#28]
On v0.7.1; Related to [Issue 18](https://github.com/taleinat/fuzzysearch/issues/18) and [Issue 27](https://github.com/taleinat/fuzzysearch/issues/27)

I would expect a call to find_near_matches with looser constraints to return a superset of what a call with more restrictive constraints returns. But that's not the case:
```py
text_to_search_for = "death"
text_to_search_in = "after de t, is candy"

matches = find_near_matches(text_to_search_for, text_to_search_in, max_l_dist=2, max_substitutions=1, max_insertions=0, max_deletions=2)
print(f"Matches with more constraints:\n{matches}")

matches = find_near_matches(text_to_search_for, text_to_search_in, max_l_dist=2, max_substitutions=2, max_insertions=2, max_deletions=2)
# which is equivalent to:
#  matches = find_near_matches(text_to_search_for, text_to_search_in, max_l_dist=2)
print(f"Matches with less constraints:\n{matches}")
```
outputs
```
Matches with more constraints:
[Match(start=6, end=10, dist=2, matched='de t')]
Matches with less constraints:
[Match(start=6, end=11, dist=2, matched='de t,')]
```
In the case with less constraints I would have expected `matches` to also include
`Match(start=6, end=10, dist=2, matched='de t')`
like
```
Matches with less constraints:
[Match(start=6, end=10, dist=2, matched='de t'), Match(start=6, end=11, dist=2, matched='de t,')]
```

**Comment by taleinat** [comment]
Hi @DanielBiskup,

`find_near_matches()` avoids returning overlapping matches. Instead, it consolidates groups of overlapping matches, and returns the "best" of each group: the match with the lowest distance, and of those, the longest match.

The various internal search functions will behave more closely to your expectations, but differ in exactly which results they will return. Some of them will not exhaustively return all options.

For some more details, see [the usage page in the docs](https://github.com/taleinat/fuzzysearch/blob/55fc21e469495bc84fe6f81b0c148e105765182d/docs/usage.rst).
