### ISSUE TITLE
To find primer sequence

### ISSUE THREAD

**Issue by hmyh1202** [taleinat/fuzzysearch#31]
Hi，
I want to use the package to find primer sequence in my sequencing data.
How to set the  parameter for detecting the local primer sequence ?
Thank U!

**Comment by taleinat** [comment]
Hi @hmyh1202,

That's well outside the scope of my domain of expertise. You'll be better served asking this in a forum dedicated to bioinformatics. I'm sorry that I can point you towards one, as that's not an area in which I work.

As this is not a bug report nor a suggestion for improvement, I'm closing this issue. (If you find the documentation lacking or unclear, you're always more than welcome to open an issue about that.)
