### ISSUE TITLE
Not able to use regex like compiled expression

### ISSUE THREAD

**Issue by prabhatM** [taleinat/fuzzysearch#33]
Hi, an we search with regex compile like expressions?

**Comment by taleinat** [comment]
Hi, no, this library does not support any syntax resembling regular expressions.

Have you taken a look at the [regex](https://pypi.org/project/regex/) library, which [supports partial matches](https://pypi.org/project/regex/#added-partial-matches-hg-issue-102)?

**Comment by prabhatM** [comment]
Thank you for the tip.

Be safe.

Regards

Prabhat
