### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by peterthorpe5** [taleinat/fuzzysearch#34]
Hi Tal,

Many years ago you put this tool forward for Biopython and I said I would like to see it in there. At the time I could not give you an example of how I would use it. Well, now I have - fuzzy matching peptide/ proteomics data.... Thank you. It just worked!!!

Nice one. 

Pete

**Comment by taleinat** [comment]
Hi Peter,

Many thanks for such warm feedback! It's great to see the work that went into this bearing fruit :)

If you'd be wiiling to mention this on a blog, Twitter etc., that would be great! (I'm @taleinat on twitter.)
