### ISSUE TITLE
Option for matching the exact value

### ISSUE THREAD

**Issue by prabhatM** [taleinat/fuzzysearch#35]
Hi,

I love the speed. But many a time, we need to match the "exact value" like in Python REGEX, for example picking up "single digit number" or two character abbreviations in some cases represent a particular value/meaning in a few domains.

**Comment by taleinat** [comment]
Hi @prabhatM,

I'm happy that the speed and utility of this library are useful for you!

Indeed, fuzzysearch does not support searches such as "two consecutive characters" or "any single digit". These are outside of the domain of problems that this library is intended to solve.

As I mentioned on issue #33, you should be able to handle such situations using the [regex](https://pypi.org/project/regex/) library, though you will have to learn its syntax.
